### ISSUE TITLE
DOCKER IMAGE BUILT BUT API END POINT IS NOT RUNNING

### ISSUE THREAD

**Issue by tutul2010** [DonSchenck/qotd-csharp#6]
Hi ,

Below is openshift details what i am using  ( redhat openshift developer sandbox)
Client Version: 4.9.0
Server Version: 4.10.3
Kubernetes Version: v1.23.3+e419edf
I successfully deployed Git master branch with docker file but api end points are not working as expected. It gave http 503 error page When i tried to access api endpoints as https://qotd-csharp-git-tutul-2010-dev.apps.sandbox-xxx/Quote/

Any help appreciate

Thanks,

**Comment by DonSchenck** [comment]
My apologies: Use the "on8080" branch for the correct results.

**Comment by tutul2010** [comment]
Thanks . it is working now
